In [ ]:
import random
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import svm


data_num = 100

x_all = []
y_all = []

for i in range(0, data_num):
    x_all.append([random.randint(0, 10), random.uniform(0, 10), random.uniform(0, 10)])
    y_all.append(random.choice([-1, 1]))

x_train, x_test, y_train, y_test = train_test_split(x_all, y_all, random_state=1)

clf = svm.SVC()
clf.fit(x_train, y_train)

prediction_train = clf.predict(x_train)
prediction_test = clf.predict(x_test)
print('[Train Set] prediction and real:')
print(list(zip(prediction_train, y_train))[:6])
print('[Test Set] prediction and real:')
print(list(zip(prediction_test, y_test))[:6])

score_train = clf.score(x_train, y_train)
score_test = clf.score(x_test, y_test)
print('[Train Set] Data Number: {}, Score {}'.format(len(y_train), score_train))
print('[Test  Set] Data Number: {}, Score {}'.format(len(y_test), score_test))


In [ ]:
# One-hot coding

from sklearn.feature_extraction import DictVectorizer


measurements = [
    {'city': 'Dubai', 'temperature': 33.},
    {'city': 'London', 'temperature': 12.},
    {'city': 'San Fransisco', 'temperature': 18.}
]

vec = DictVectorizer()

print(vec.fit_transform(measurements).toarray())
print(vec.get_feature_names())


In [ ]:
# Standardization, or mean removal and variance scaling

from sklearn import preprocessing
import numpy as np


X = np.array([[ 1., -10.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  10., -1.]])

X_scaled = preprocessing.scale(X)
print(X_scaled)                                          
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X)
print(min_max_scaler.scale_)
print(min_max_scaler.min_)
print(X_train_minmax)
print(X_train_minmax.mean(axis=0))
print(X_train_minmax.std(axis=0))

max_abs_scaler = preprocessing.MaxAbsScaler()
X_train_maxabs = max_abs_scaler.fit_transform(X)
print(X_train_maxabs)
print(X_train_maxabs.mean(axis=0))
print(X_train_maxabs.std(axis=0))


In [ ]:
# Normalization

from sklearn import preprocessing
import numpy as np


X = np.array([[ 1., -10.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  10., -1.]])

X_normalized = preprocessing.normalize(X)
print(X_normalized)
print(X_normalized.mean(axis=0))
print(X_normalized.std(axis=0))

In [29]:
# Binarization

from sklearn import preprocessing
import numpy as np


X = np.array([[ 1., -10.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  10., -1.]])

binarizer = preprocessing.Binarizer()
# binarizer = preprocessing.Binarizer(threshold=1.1)

X_binarizered = binarizer.transform(X)
print(X_binarizered)


[[ 1.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
